# supports load balancing over multiple minigrpc services:
# docker-compose up --build --force-recreate --scale minigrpc=5
#
# test with:
# grpcurl -plaintext -d '{ "name":"whatever" }' localhost:10000 greet.Greeter.SayHello

version: "3"

services:
  proxy:
    image: envoyproxy/envoy-alpine:v1.21.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ${CERT_DIR}:/https:ro
    ports:
      - 10000:10000 # http
      - 10001:10001 # https
  minigrpc:
    image: minigrpc
    build:
      context: ./minigrpc
      dockerfile: Dockerfile
    volumes:
      - ${CERT_DIR}:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5022;https://+:5023
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
